apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeturbo
  namespace: turbo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeturbo
  template:
    metadata:
      annotations:
        kubeturbo.io/monitored: "false"
      labels:
        app.kubernetes.io/name: kubeturbo
    spec:
      containers:
      - args:
        - --turboconfig=/etc/kubeturbo/turbo.config
        - --v=2
        - --kubelet-https=true
        - --kubelet-port=10250
        env:
        - name: KUBETURBO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: turbonomic/kubeturbo:8.3.2
        name: kubeturbo
        volumeMounts:
        - mountPath: /etc/kubeturbo
          name: turbo-volume
          readOnly: true
        - mountPath: /etc/turbonomic-credentials
          name: turbonomic-credentials-volume
          readOnly: true
        - mountPath: /var/log
          name: varlog
      restartPolicy: Always
      serviceAccountName: turbo-user
      volumes:
      - configMap:
          name: turbo-config
        name: turbo-volume
      - name: turbonomic-credentials-volume
        secret:
          defaultMode: 420
          optional: true
          secretName: turbonomic-credentials
      - emptyDir: {}
        name: varlog
